/** دسته‌بندی‌ها و محصولات نمونه. تصاویر از Unsplash (لینک عمومی). قیمت‌ها به تومان. */
export const categories = [
  { name: 'گیاهان دارویی', icon: 'leaf', order: 1, description: 'گیاهان خشک و دم‌کردنی با کیفیت مزرعه‌ای', image: { url: '/images/products/avishan-shirazi.jpg' } },
  { name: 'ادویه‌ها', icon: 'spice', order: 2, description: 'ادویه تازه آسیاب‌شده و دانه‌ای', image: { url: '/images/products/spice-selection.jpg' } },
  { name: 'عرقیات گیاهی', icon: 'droplet', order: 3, description: 'عرقیات تقطیر سنتی در شیشه دربسته', image: { url: '/images/products/oils-distillates.jpg' } },
  { name: 'دمنوش‌ها', icon: 'cup', order: 4, description: 'ترکیب‌های دمنوش برای آرامش و انرژی', image: { url: '/images/products/damnoosh-aramesh-shab.jpg' } },
  { name: 'خشکبار', icon: 'nut', order: 5, description: 'آجیل و خشکبار تازه بوداده', image: { url: '/images/products/nuts-natural.jpg' } },
  { name: 'روغن‌های گیاهی', icon: 'oil', order: 6, description: 'روغن پرس سرد بدون افزودنی', image: { url: '/images/products/oils-distillates.jpg' } },
  { name: 'محصولات طبیعی', icon: 'honey', order: 7, description: 'عسل، گلاب و فرآورده‌های طبیعی', image: { url: '/images/products/nuts-natural.jpg' } },
  { name: 'برنج و غلات', icon: 'grain', order: 8, description: 'برنج ایرانی و غلات انتخاب‌شده', image: { url: '/images/products/nuts-natural.jpg' } },
  { name: 'محصولات ویژه', icon: 'star', order: 9, description: 'برنج، ادویه‌های ارگانیک و پرمصرف', image: { url: '/images/products/zaferan-sargol.jpg' } },
];

/** تصویر محلی داخل frontend/public/images؛ بدون وابستگی به CDN بیرونی. */
const local = (file, alt = '') => [{ url: `/images/products/${file}.jpg`, alt }];

export const products = [
  { name: 'گل گاوزبان ایرانی', category: 'گیاهان دارویی', price: 148000, discount: 15, stock: 64, weight: 100, origin: 'گیلان', shortDescription: 'گل درشت و خوش‌رنگ، دم‌کرده‌ای آرام‌بخش', description: 'گل گاوزبان دست‌چین از مزارع شمال کشور، بدون ساقه اضافه و با رنگ بنفش زنده. برای دم‌نوش شب و کاهش تنش روزانه انتخاب اول است. در بسته‌بندی زیپ‌دار و دارای دریچه یک‌طرفه ارسال می‌شود.', ingredients: ['گل گاوزبان خشک'], usage: 'یک قاشق مرباخوری در ۲۰۰ میلی‌لیتر آب جوش، ۷ دقیقه دم بکشد.', benefits: ['کاهش استرس', 'کمک به خواب راحت', 'حس آرامش'], isFeatured: true, isPopular: true, images: [{ url: '/images/products/dedicated/01-gol-gavzaban-irani.webp', alt: 'گل گاوزبان ایرانی' }] },
  { name: 'بابونه آلمانی', category: 'گیاهان دارویی', price: 96000, discount: 0, stock: 88, weight: 100, origin: 'اصفهان', shortDescription: 'گل کامل بابونه با عطر سیب', description: 'بابونه آلمانی با گل‌های کامل و عطر شبیه سیب. دم‌کرده روشن و خوش‌طعم می‌دهد و برای معده و آرامش عصر عالی است.', ingredients: ['گل بابونه'], usage: 'یک قاشق در آب جوش، ۵ دقیقه سرپوشیده دم بکشد.', benefits: ['آرام‌بخش', 'کمک به هاضمه', 'ضدنفخ'], isPopular: true, images: [{ url: '/images/products/dedicated/02-babouneh-almani.webp', alt: 'بابونه آلمانی' }] },
  { name: 'آویشن شیرازی', category: 'گیاهان دارویی', price: 112000, discount: 10, stock: 51, weight: 100, origin: 'شیراز', shortDescription: 'آویشن کوهی با اسانس بالا', description: 'آویشن شیرازی برداشت بهاره، برگ‌ریز و پر اسانس. هم برای دم‌نوش سرماخوردگی و هم چاشنی غذا کاربرد دارد.', ingredients: ['آویشن شیرازی'], usage: 'برای دم‌نوش نصف قاشق، برای چاشنی روی غذای گرم بپاشید.', benefits: ['کمک به تنفس', 'ضدسرفه', 'آنتی‌اکسیدان'], isFeatured: true, images: [{ url: '/images/products/dedicated/03-avishan-shirazi.webp', alt: 'آویشن شیرازی' }] },
  { name: 'نعناع خشک ممتاز', category: 'گیاهان دارویی', price: 74000, discount: 0, stock: 120, weight: 80, origin: 'کاشان', shortDescription: 'برگ نعناع سبز و معطر', description: 'نعناع سایه‌خشک که رنگ سبز و عطر خود را نگه داشته است. برای آبدوغ‌خیار، کوفته و دم‌نوش معده.', ingredients: ['برگ نعناع'], usage: 'به‌صورت چاشنی یا یک قاشق در آب جوش.', benefits: ['رفع نفخ', 'خوش‌طعم', 'خنک‌کننده'], images: [{ url: '/images/products/dedicated/04-nanaa-khoshk-momtaz.webp', alt: 'نعناع خشک ممتاز' }] },
  { name: 'چای ترش (چای سبز کرکدی)', category: 'دمنوش‌ها', price: 89000, discount: 20, stock: 43, weight: 100, origin: 'گیلان', shortDescription: 'دم‌نوش سرخ با طعم مطبوع ترش', description: 'گل‌های خشک چای ترش با رنگ‌دهی قوی. یک لیوان آن رنگ یاقوتی زیبایی می‌دهد و سرد هم نوشیدنی خوبی است.', ingredients: ['گل چای ترش'], usage: 'یک قاشق در آب جوش، ۶ دقیقه.', benefits: ['کمک به فشار خون', 'سرشار از آنتی‌اکسیدان'], isFeatured: true, images: [{ url: '/images/products/dedicated/05-chai-torsh-karkadi.webp', alt: 'چای ترش (چای سبز کرکدی)' }] },
  { name: 'دمنوش آرامش شب', category: 'دمنوش‌ها', price: 168000, discount: 12, stock: 37, weight: 120, origin: 'ترکیب اختصاصی', shortDescription: 'ترکیب گاوزبان، بابونه و اسطوخودوس', description: 'ترکیب اختصاصی عطاری برای پایان روز: گل گاوزبان، بابونه، اسطوخودوس و کمی بهارنارنج. طعم گلی ملایم با شیرینی طبیعی.', ingredients: ['گل گاوزبان', 'بابونه', 'اسطوخودوس', 'بهارنارنج'], usage: 'یک قاشق غذاخوری، ۸ دقیقه سرپوشیده.', benefits: ['خواب عمیق‌تر', 'کاهش تنش', 'بدون کافئین'], isFeatured: true, isPopular: true, images: [{ url: '/images/products/dedicated/06-damnoosh-aramesh-shab.webp', alt: 'دمنوش آرامش شب' }] },
  { name: 'دمنوش زنجبیل و لیمو', category: 'دمنوش‌ها', price: 132000, discount: 0, stock: 59, weight: 100, shortDescription: 'گرم‌کننده با تندی ملایم', description: 'زنجبیل خلالی با لیموعمانی و کمی دارچین. برای روزهای سرد و بعد از غذای سنگین.', ingredients: ['زنجبیل', 'لیمو عمانی', 'دارچین'], usage: 'یک قاشق در آب جوش، ۱۰ دقیقه.', benefits: ['گرم‌کننده', 'کمک به گوارش'], isPopular: true, images: [{ url: '/images/products/dedicated/07-damnoosh-zanjebil-limoo.webp', alt: 'دمنوش زنجبیل و لیمو' }] },
  { name: 'چای سبز ایرانی لاهیجان', category: 'دمنوش‌ها', price: 158000, discount: 8, stock: 72, weight: 200, origin: 'لاهیجان', shortDescription: 'چین اول، برگ سبز پیچیده', description: 'چای سبز چین اول لاهیجان با برگ‌های پیچیده و عطر تازه. دم‌کرده روشن و بدون تلخی اضافه.', ingredients: ['چای سبز'], usage: 'آب ۸۰ درجه، ۲ تا ۳ دقیقه.', benefits: ['متابولیسم', 'آنتی‌اکسیدان', 'انرژی ملایم'], images: [{ url: '/images/products/dedicated/08-chai-sabz-lahijan.webp', alt: 'چای سبز ایرانی لاهیجان' }] },
  { name: 'دارچین سیلان چوبی', category: 'ادویه‌ها', price: 138000, discount: 0, stock: 66, weight: 100, origin: 'سریلانکا', shortDescription: 'لوله‌های نازک با شیرینی طبیعی', description: 'دارچین سیلان اصل با پوست نازک و طعم شیرین و ملایم، متفاوت با دارچین کاسیا. مناسب دم‌نوش و شیرینی‌پزی.', ingredients: ['چوب دارچین سیلان'], usage: 'یک تکه در دم‌نوش یا آسیاب برای شیرینی.', benefits: ['تعادل قند خون', 'خوش‌عطر'], isFeatured: true, images: [{ url: '/images/products/dedicated/09-darchin-seylan.webp', alt: 'دارچین سیلان چوبی' }] },
  { name: 'برنج هاشمی ارگانیک گیلان', category: 'برنج و غلات', price: 398000, discount: 8, stock: 42, weight: 1000, unit: 'گرم', origin: 'گیلان', shortDescription: 'دانه‌بلند، خوش‌عطر و مناسب مصرف روزانه', description: 'برنج هاشمی ارگانیک گیلان با عطر طبیعی و پخت یکدست؛ انتخابی روزمره برای سفره ایرانی، بدون عطر و افزودنی مصنوعی.', ingredients: ['برنج هاشمی'], usage: 'پیش از پخت چند بار با آب سرد بشویید و طبق روش دلخواه دم کنید.', benefits: ['مصرف روزانه', 'عطر طبیعی', 'پخت یکدست'], isFeatured: true, isPopular: true, images: [{ url: '/images/products/dedicated/25-berenj-hashemi-organic.webp', alt: 'برنج هاشمی ارگانیک گیلان' }] },
  { name: 'برنج طارم هاشمی ممتاز', category: 'برنج و غلات', price: 468000, discount: 10, stock: 36, weight: 1000, unit: 'گرم', origin: 'استان مازندران', shortDescription: 'خوش‌عطر، دانه‌بلند و مجلسی', description: 'برنج طارم هاشمی ممتاز با عطر طبیعی و قدکشیدن خوب بعد از پخت؛ انتخابی مجلسی برای چلو و مهمانی، بدون عطر و افزودنی مصنوعی.', ingredients: ['برنج طارم', 'برنج هاشمی'], usage: 'برنج را چند بار بشویید، ۲ تا ۳ ساعت بخیسانید و سپس به روش دلخواه دم کنید.', benefits: ['قدکشیدن عالی', 'عطر طبیعی', 'مناسب مهمانی'], isFeatured: true, isPopular: true, images: [{ url: '/images/products/dedicated/26-berenj-tarom-hashemi.webp', alt: 'برنج طارم هاشمی ممتاز' }] },
  { name: 'برنج دمسیاه آستانه ممتاز', category: 'برنج و غلات', price: 498000, discount: 8, stock: 28, weight: 1000, unit: 'گرم', origin: 'آستانه اشرفیه، گیلان', shortDescription: 'معطر، خوش‌پخت و اصیل گیلانی', description: 'برنج دمسیاه آستانه ممتاز از برنج‌های خوش‌عطر گیلان؛ با پخت نرم و دانه‌های کشیده برای سفره‌ای اصیل و خوش‌طعم.', ingredients: ['برنج دمسیاه'], usage: 'پیش از پخت چند بار با آب سرد بشویید، بخیسانید و با حرارت ملایم دم کنید.', benefits: ['عطر اصیل گیلانی', 'پخت نرم', 'مناسب چلو'], isFeatured: true, isPopular: true, images: [{ url: '/images/products/dedicated/27-berenj-domsiah-estaneh.webp', alt: 'برنج دمسیاه آستانه ممتاز' }] },
  { name: 'زعفران سرگل درجه یک', category: 'محصولات ویژه', price: 1180000, discount: 5, stock: 24, weight: 4, origin: 'قائنات', shortDescription: 'سرگل قائنات، رنگ بالا', description: 'زعفران سرگل قائنات با رشته‌های یکدست و قدرت رنگ‌دهی بالا. در بسته‌بندی شیشه‌ای درب‌دار و به‌همراه برگه اصالت.', ingredients: ['زعفران سرگل'], usage: 'ساییده و در آب گرم یا یخ حل کنید.', benefits: ['رنگ و عطر قوی', 'روحیه‌بخش'], isFeatured: true, isPopular: true, images: [{ url: '/images/products/dedicated/10-zaferan-sargol.webp', alt: 'زعفران سرگل درجه یک' }] },
  { name: 'هل سبز درشت', category: 'ادویه‌ها', price: 690000, discount: 10, stock: 18, weight: 100, origin: 'هند', shortDescription: 'هل سبز خوش‌عطر و پر دانه', description: 'هل سبز درشت با پوست سالم و دانه‌های تیره و روغنی. عطر آن در چای و شیرینی فوری حس می‌شود.', ingredients: ['هل سبز'], usage: 'دو عدد در قوری چای یا آسیاب‌شده در شیرینی.', benefits: ['خوش‌طعم‌کننده', 'کمک به گوارش'], images: [{ url: '/images/products/dedicated/11-hel-sabz-dorosht.webp', alt: 'هل سبز درشت' }] },
  { name: 'زردچوبه ارگانیک', category: 'ادویه‌ها', price: 68000, discount: 0, stock: 140, weight: 200, shortDescription: 'رنگ نارنجی زنده، بدون افزودنی', description: 'زردچوبه آسیاب‌شده با کورکومین بالا و رنگ نارنجی روشن. بدون آرد و رنگ افزوده.', ingredients: ['زردچوبه'], usage: 'در پایه غذا همراه پیاز داغ.', benefits: ['ضدالتهاب', 'آنتی‌اکسیدان'], images: [{ url: '/images/products/dedicated/12-zardchube-organic.webp', alt: 'زردچوبه ارگانیک' }] },
  { name: 'سماق ایرانی دانه‌ای', category: 'ادویه‌ها', price: 82000, discount: 15, stock: 95, weight: 200, shortDescription: 'ترشی طبیعی و رنگ تیره', description: 'سماق دانه‌ای تازه با ترشی طبیعی. برای کباب و آش، هم دانه و هم آسیاب‌شده قابل استفاده است.', ingredients: ['سماق'], usage: 'روی کباب یا در آش.', benefits: ['ترش‌کننده طبیعی', 'آنتی‌اکسیدان'], images: [{ url: '/images/products/dedicated/13-somagh-irani.webp', alt: 'سماق ایرانی دانه‌ای' }] },
  { name: 'عرق نعناع دو آتشه', category: 'عرقیات گیاهی', price: 78000, discount: 0, stock: 110, weight: 1000, unit: 'میلی‌لیتر', shortDescription: 'تقطیر سنتی، بدون اسانس', description: 'عرق نعناع دو آتشه با روش تقطیر سنتی مسی. شفاف و پر عطر، بدون اسانس و افزودنی.', ingredients: ['نعناع', 'آب'], usage: 'نصف استکان بعد از غذا.', benefits: ['رفع نفخ', 'آرامش معده'], isPopular: true, images: [{ url: '/images/products/dedicated/14-arag-nanaa-do-atash.webp', alt: 'عرق نعناع دو آتشه' }] },
  { name: 'عرق کاسنی', category: 'عرقیات گیاهی', price: 74000, discount: 0, stock: 98, weight: 1000, unit: 'میلی‌لیتر', shortDescription: 'خنک و تلخ ملایم', description: 'عرق کاسنی خالص با طعم تلخ ملایم، انتخاب رایج برای پاکسازی و روزهای گرم. اغلب همراه شاه‌تره مصرف می‌شود.', ingredients: ['کاسنی', 'آب'], usage: 'یک استکان صبح ناشتا.', benefits: ['خنک‌کننده', 'کمک به کبد'], images: [{ url: '/images/products/dedicated/15-arag-kasni.webp', alt: 'عرق کاسنی' }] },
  { name: 'عرق بهارنارنج', category: 'عرقیات گیاهی', price: 96000, discount: 10, stock: 64, weight: 1000, unit: 'میلی‌لیتر', origin: 'شیراز', shortDescription: 'عطر شکوفه مرکبات', description: 'عرق بهارنارنج شیراز از شکوفه تازه. عطر آن قوی است و برای آرامش و بی‌قراری استفاده می‌شود.', ingredients: ['شکوفه بهارنارنج', 'آب'], usage: 'نصف استکان قبل از خواب.', benefits: ['آرام‌بخش', 'خوش‌عطر'], isFeatured: true, images: [{ url: '/images/products/dedicated/16-arag-baharanarنج.webp', alt: 'عرق بهارنارنج' }] },
  { name: 'روغن سیاه‌دانه پرس سرد', category: 'روغن‌های گیاهی', price: 248000, discount: 12, stock: 46, weight: 250, unit: 'میلی‌لیتر', shortDescription: 'پرس سرد، شیشه تیره', description: 'روغن سیاه‌دانه پرس سرد در شیشه تیره برای محافظت از نور. طعم تند و مشخص، بدون تصفیه شیمیایی.', ingredients: ['دانه سیاه‌دانه'], usage: 'روزی یک قاشق مرباخوری.', benefits: ['تقویت ایمنی', 'ضدالتهاب'], isFeatured: true, isPopular: true, images: [{ url: '/images/products/dedicated/17-roghan-siah-daneh.webp', alt: 'روغن سیاه‌دانه پرس سرد' }] },
  { name: 'روغن کنجد بو داده', category: 'روغن‌های گیاهی', price: 196000, discount: 0, stock: 58, weight: 500, unit: 'میلی‌لیتر', shortDescription: 'عطر کنجد برشته', description: 'روغن کنجد از دانه بوداده با عطر گرم و طعم آجیلی. برای پخت و پز و ماساژ.', ingredients: ['کنجد'], usage: 'پخت و پز یا مصرف مستقیم.', benefits: ['منبع ویتامین E', 'مناسب پوست'], images: [{ url: '/images/products/dedicated/18-roghan-konjed.webp', alt: 'روغن کنجد بو داده' }] },
  { name: 'روغن بادام شیرین', category: 'روغن‌های گیاهی', price: 218000, discount: 8, stock: 39, weight: 250, unit: 'میلی‌لیتر', shortDescription: 'سبک و بی‌بو برای پوست و مو', description: 'روغن بادام شیرین پرس سرد، سبک و کم‌بو. جذب سریع و مناسب پوست خشک و مو.', ingredients: ['بادام شیرین'], usage: 'روی پوست یا مو، چند قطره.', benefits: ['نرم‌کننده پوست', 'تقویت مو'], images: [{ url: '/images/products/dedicated/19-roghan-badam-shirin.webp', alt: 'روغن بادام شیرین' }] },
  { name: 'پسته اکبری خندان', category: 'خشکبار', price: 890000, discount: 10, stock: 31, weight: 500, origin: 'رفسنجان', shortDescription: 'دانه درشت، شور ملایم', description: 'پسته اکبری رفسنجان با دانه درشت و خنده کامل، نمک ملایم و تازه بوداده در هفته ارسال.', ingredients: ['پسته', 'نمک دریا'], usage: 'مصرف مستقیم.', benefits: ['منبع پروتئین', 'چربی سالم'], isFeatured: true, isPopular: true, images: [{ url: '/images/products/dedicated/20-pesteh-akbari.webp', alt: 'پسته اکبری خندان' }] },
  { name: 'بادام درختی مامایی', category: 'خشکبار', price: 620000, discount: 0, stock: 44, weight: 500, shortDescription: 'مغز کامل و ترد', description: 'بادام مامایی با مغز کامل و ترد. بوداده خشک بدون روغن.', ingredients: ['بادام'], usage: 'مصرف مستقیم یا در شیرینی.', benefits: ['منبع منیزیم', 'سیرکننده'], images: [{ url: '/images/products/dedicated/21-badam-mamaei.webp', alt: 'بادام درختی مامایی' }] },
  { name: 'توت خشک سفید', category: 'خشکبار', price: 178000, discount: 15, stock: 76, weight: 400, shortDescription: 'شیرینی طبیعی بدون شکر', description: 'توت خشک سفید تمیز و بدون چوب. جایگزین خوبی برای شیرینی و قند در چای.', ingredients: ['توت خشک'], usage: 'همراه چای یا در ترکیب آجیل.', benefits: ['انرژی سریع', 'بدون شکر افزوده'], isPopular: true, images: [{ url: '/images/products/dedicated/22-toot-khoshk-sefid.webp', alt: 'توت خشک سفید' }] },
  { name: 'عسل کوهی چهل‌گیاه', category: 'محصولات طبیعی', price: 480000, discount: 0, stock: 35, weight: 900, shortDescription: 'خام، رس‌بسته طبیعی', description: 'عسل چهل‌گیاه از ارتفاعات با ساکارز پایین. خام و بدون حرارت، طبیعی است که با گذر زمان رس ببندد.', ingredients: ['عسل خام'], usage: 'یک قاشق در روز، آب گرم زیر ۴۰ درجه.', benefits: ['انرژی طبیعی', 'تقویت ایمنی'], isFeatured: true, images: [{ url: '/images/products/dedicated/23-asal-koohi.webp', alt: 'عسل کوهی چهل‌گیاه' }] },
  { name: 'گلاب دو آتشه قمصر', category: 'محصولات طبیعی', price: 128000, discount: 5, stock: 82, weight: 1000, unit: 'میلی‌لیتر', origin: 'قمصر کاشان', shortDescription: 'تقطیر گل محمدی قمصر', description: 'گلاب دو آتشه از گل محمدی قمصر کاشان. عطر ماندگار برای شیرینی، دم‌نوش و شربت.', ingredients: ['گل محمدی', 'آب'], usage: 'در شیرینی، چای یا شربت.', benefits: ['آرام‌بخش', 'خوش‌عطر'], isPopular: true, images: [{ url: '/images/products/dedicated/24-golab-do-atash.webp', alt: 'گلاب دو آتشه قمصر' }] },
];

export const seedUsers = [
  { name: 'مریم رضایی', email: 'maryam@example.com', phone: '09121110001', password: 'Attari@1404' },
  { name: 'سینا کاظمی', email: 'sina@example.com', phone: '09121110002', password: 'Attari@1404' },
  { name: 'نگار موسوی', email: 'negar@example.com', phone: '09121110003', password: 'Attari@1404' },
];

export const seedReviews = [
  { rating: 5, title: 'عالی بود', comment: 'بسته‌بندی مرتب و عطر گل واقعاً تازه بود. دم‌کرده رنگ خوبی داد.' },
  { rating: 4, title: 'راضی‌ام', comment: 'کیفیت خوب، ارسال کمی طول کشید ولی سالم رسید.' },
  { rating: 5, title: 'دوباره می‌خرم', comment: 'با چیزی که از عطاری محل می‌گرفتم قابل مقایسه نیست، خیلی تمیزتر.' },
  { rating: 3, title: 'متوسط', comment: 'خوب بود اما انتظار داشتم مقدار بیشتری باشد.' },
];
